server:
  port: 9999
spring:
  application:
    name: "ums_gateway"
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: ums_auth_service
          uri: lb://UMS_AUTH_SERVICE
          predicates:
            - Path=/auth/**
